name: 'Serverless'

on:
#  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 执行部署脚本
      env:
          SERVERLESS_PLATFORM_VENDOR: tencent
          USERS_COVER: ${{ secrets.USERS_COVER }}
          COOKIE: ${{ secrets.COOKIE }}
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
      run: |
          echo "$COOKIE" > ./cookie.txt
          echo "$USERS_COVER" > ./config.json
          sudo chmod +x ./serverless/deploy.sh
          bash ./serverless/deploy.sh

